### ISSUE TITLE
android.permission.SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by IzzySoft** [meenbeese/Chronos#13]
On today's update, my scanner report:

    ! repo/com.meenbeese.chronos_2.apk declares sensitive permission(s): android.permission.SYSTEM_ALERT_WINDOW

As it's not mentioned in the permission list with the README, may I kindly ask for the background of this? Thanks in advance!

PS: I was able to trace it back to commit 6232244fb34763f5e928acd209c3fdb24afe5ede (from 4 years ago? funny, did I miss it when setting up your app in my repo then? well, happens… good that my updater keeps watch :see_no_evil:) – but I'm not sure how to put that in a few words as explanation on the permission.

**Comment by meenbeese** [comment]
Hmm, this permission might not even be necessary anymore. Looks like it was added to bypass OEM restrictions, but that is already done by 'IGNORE_BATTERY_OPTIMIZATIONS'.

Thanks for finding the relevant commit by the way. It will help the investigation.

**Comment by IzzySoft** [comment]
Found anything yet? Just got reported again with today's update :wink:

**Comment by meenbeese** [comment]
Sorry for the late reply :( I did some initial testing and found that the app cannot function correctly without this permission. For example, alarms and timers do not work when in a different app. I might take a look in the future at what can be done to avoid this, but I have to keep this permission for now. I will add the reasoning behind this permission to the README, so everything can be clear and transparent.

**Comment by IzzySoft** [comment]
```yaml
android.permission.SYSTEM_ALERT_WINDOW: needed to launch e.g. timer alerts from background
```

This is the answer I got from another alarm clock project, which fits your description here. Will add that then for Chronos as well … done. Still no idea what it got to do with that permission, but it's not the only "strange thing" with Android perms I guess…

Thanks for checking – all clarified then.
