### ISSUE TITLE
Cannot choose bg image on A14

### ISSUE THREAD

**Issue by meenbeese** [meenbeese/Chronos#20]
Choosing a background image does not work on Pixel 8, Android 14. The error is displayed: "An error has occurred when choosing media."

**Comment by AeliusSaionji** [comment]
I suspect it's similar to the permission error with audio that has just fixed!

**Comment by AeliusSaionji** [comment]
This still isn't working for me. I grant it permissions for all media and it opens a chooser, but no matter what image I select I get a blank background.

**Comment by meenbeese** [comment]
> This still isn't working for me. I grant it permissions for all media and it opens a chooser, but no matter what image I select I get a blank background.

Click on `...` -> `Browse` -> `Recent` -> `Click on image` and it should work. I am trying to find a fix until then.
