### ISSUE TITLE
Use build config to get version in About screen

### ISSUE THREAD

**Issue by Jean-BaptisteC** [meenbeese/Chronos#25]

**Comment by Jean-BaptisteC** [comment]
Too complex
You can use `BuildConfig.VERSION_NAME`

**Comment by meenbeese** [comment]
Yes you're right. That is easier and I tried fetching it like that but always failed with some error like this:
`file:///C:/Users/meenbeese/GitHub/Chronos/app/src/main/java/com/meenbeese/chronos/data/preference/AboutPreferenceData.kt:11:30 Unresolved reference: BuildConfig`

For some reason, my Gradle does not generate the required BuildConfig property even when I explicitly specify
`
buildFeatures {
        buildConfig = true
}
`

Perhaps you can take a look and submit a PR if there is an easy fix?
