### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Alex-Vay** [meenbeese/Chronos#32]
When I want to build app in android studio I get:
```
Configuration cache state could not be cached: field `__librarySourceSets__` of task `:app:mapDebugSourceSetPaths` of type `com.android.build.gradle.tasks.MapSourceSetPathsTask`: error writing value of type 'org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection'
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find me.jahirfiquitiva:FABsMenu:1.1.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/me/jahirfiquitiva/FABsMenu/1.1.4/FABsMenu-1.1.4.pom
       - https://jcenter.bintray.com/me/jahirfiquitiva/FABsMenu/1.1.4/FABsMenu-1.1.4.pom
       - https://jitpack.io/me/jahirfiquitiva/FABsMenu/1.1.4/FABsMenu-1.1.4.pom
     Required by:
         project :app
Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Please can someone help with this?

**Comment by meenbeese** [comment]
Can you try setting the configuration cachr to false in `gradle.properties`? This error has been causing the CI to fail for the last few days and I can't explain why. That said, I was planning to move away from said legacy FABsMenu library anyway, so I will try to accelerate that now.

**Comment by Alex-Vay** [comment]
Like this? Maybe I'm doing something wrong, but there are more mistakes.
![image](https://github.com/meenbeese/Chronos/assets/131193687/1a171655-4540-45bb-bcd4-351e41a6b210)

**Comment by meenbeese** [comment]
Thank you for testing it. The issue is more complicated I guess and is caused by the outdated FAB dependency, which I am currently working on replacing. One that is done, you can pull the changes from main and Gradle should build fine.

**Comment by meenbeese** [comment]
Should be fixed now! Can you try rebuilding from the latest `main` branch?

**Comment by Alex-Vay** [comment]
Thanks. Now it works perfectly
