### ISSUE TITLE
Wrong text background color on FAB

### ISSUE THREAD

**Issue by Jean-BaptisteC** [meenbeese/Chronos#43]
## How to Reproduce

- Press main FAB button
<img src="https://github.com/meenbeese/Chronos/assets/87148630/f2bf4517-6185-48f9-b4d3-b99539fe9d1f" height=400 /><img src="https://github.com/meenbeese/Chronos/assets/87148630/8f4e0f13-64c0-43b2-bfc5-271c1aec1eb2" height=400 />

## Info

- Device model: `Pixel 6`
- Android version: `Android 14`
- App version: `main`

**Comment by Jean-BaptisteC** [comment]
Problem is not fixed in 1.5.0 version

**Comment by meenbeese** [comment]
> Problem is not fixed in 1.5.0 version

Force stop + restart seems to resolve it? I can force this every time users change the theme.

**Comment by Jean-BaptisteC** [comment]
Yes, force stop fixed the problem
