### ISSUE TITLE
Use native splashscreen

### ISSUE THREAD

**Issue by Jean-BaptisteC** [meenbeese/Chronos#45]
https://developer.android.com/training/wearables/apps/splash-screen

**Comment by meenbeese** [comment]
What is wrong with the current implementation? Is it too custom?

**Comment by ok-ttc** [comment]
Not sure of that's related. One thing that nags me a little when I end an alarm is that it opens the app. I would prefer the app to stay closed after shutting the alarm down from the alarm screen and retain the state the phone was in before the alarm went off.

**Comment by meenbeese** [comment]
> Not sure if that's related. One thing that nags me a little when I end an alarm is that it opens the app. I would prefer the app to stay closed after shutting the alarm down from the alarm screen and retain the state the phone was in before the alarm went off.

Thanks for the feedback, but it is not really related to this issue so I opened a new one. In principle, issues should handle one task only, so as to keep things tidy :)

**Comment by Jean-BaptisteC** [comment]
On most recent devices, we have 2 splashscreens:
- The native splashscreen
- The custom splashscreen

It would be great to keep only one splashscreen, but native splashscreen is too basic, you can only specify the icon shown and the background color. It's not possible to use animation on splashscreen.
