### ISSUE TITLE
Sunset and sunrise time based on current location

### ISSUE THREAD

**Issue by Today20092** [meenbeese/Chronos#56]
Sunrise and sunset time can be based on the phones current location.

Also it would be nice if there was a feature where you can set an alarm based on the sunrise and sunset time, like 10 minutes before or after or however long.

**Comment by meenbeese** [comment]
This is not really planned, sorry. I don't see much value in adding an extra permission and adding extra complexity to the codebase when it is trivial to look up and input sunrise/sunset times on your own.
