### ISSUE TITLE
Fastlane changelogs

### ISSUE THREAD

**Issue by IzzySoft** [meenbeese/Chronos#58]
Just to inform you that per-release changelogs in Fastlane are limited to 500 chars, and all beyond that is cut off even if mid-word.

    ! metadata/com.meenbeese.chronos/en-US/changelogs/6.txt has 540 chars

This will be a "cutting candidate". Please take care for future ones :wink:

**Comment by meenbeese** [comment]
Thanks for the warning, I did not know this was a thing. I guess copy pasting the GitHub changelog is not the best strategy 😁

**Comment by IzzySoft** [comment]
> I did not know this was a thing

Yeah, things can get tricky, especially if there's no easy documentation. There are other limits, too, so to be on the safe side, be welcome to check with the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) :smiley:

> I guess copy pasting the GitHub changelog is not the best strategy

No, not really. Best strategy is to include the most important details (especially things we should read **before** updating, like "breaking changes"), and end that with something like "find the full changelog at {url}", pointing to the latter. Background is that this per-release changelog is intended for "inline display", usually close to the app's description – as you can see with the apps at the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid). Checkout [Chronos](https://apt.izzysoft.de/fdroid/index/apk/com.meenbeese.chronos) for example, and you see a) what I mean and b) why this limit is useful:

![image](https://github.com/meenbeese/Chronos/assets/6781438/dcc8ea3d-0af8-442b-99a7-1b20a0f13f26)

Eh, and c) what "cut of exactly at char 500" means :see_no_evil:

Btw: it's not only this repo browser showing the per-release changelog there. The official F-Droid client for Android does the same, others most likely as well (I didn't check them all).

**Comment by meenbeese** [comment]
Appreciate the detailed explanation!

**Comment by IzzySoft** [comment]
Always glad to help! :star_struck:
