### ISSUE TITLE
[BUG] Missing permission for Android 14

### ISSUE THREAD

**Issue by HarriBuh** [meenbeese/Chronos#6]
The app does not ask for the needed permission "music and audio" on Android 14, which is necessary for the alarms to work (the next screenshot was made after I manually set the allowance).

![Screenshot_20240226-211408.png](https://github.com/meenbeese/Chronos/assets/123186113/cdcb71b9-05fe-4c2d-a0ab-ce903e1377ec)

Because of this issue, I'm pretty sure that the app will always reset (= gray out) the sound alarm on saved alarms (the following screenshot does show the working sound alarm, but should be used for reference).
There still may be another reason for this behaviour, but it DOES happen anyway.

![markup_obscura1708978610155.jpg](https://github.com/meenbeese/Chronos/assets/123186113/9fba683d-961e-443f-aacc-1f3d6af3f3f6)

**Comment by meenbeese** [comment]
Thanks, I will look into this issue.

**Comment by ok-ttc** [comment]
I cannot set ringtones in the settings (defaults). I can set the ringtone in the alarm itself, but it doesn't actually play when the time comes.

In the settings it never shows what I've chosen and in the alarm it shows it but doesn't play the alarm. 

Granting the "Music and Audio" permission manually doesn't seem to help, although I can play the alarm in the preview in the picker regardless of this permission.

**Comment by m0yP** [comment]
Same here. Running Android 14 Pixel stock ROM. 

No matter what alarm you aelect in settings, it will go to none.

Alarms do vibrate and wake up screen, though. We're just missing sound.

![Screenshot_20240309-190435](https://github.com/meenbeese/Chronos/assets/22119314/99d48169-2644-4863-b403-768668e28142)

**Comment by graphixillusion** [comment]
I have the same problem under Android 9. The permission's section is grayed out and i'm my case i have no sound and no vibration too.

**Comment by spoodfoilage** [comment]
Same problem here, Pixel 5 with Android 14.  I had to open settings and set the permission myself.  Even then, the general app settings do not accept any choices for default sounds (ringtone and timer).  I can however get around this and choose an alarm sound from within each individual alarm setting.

**Comment by meenbeese** [comment]
> @meenbeese Have you even looked at this issue once yet?

Yes, obviously :) This is a release blocker and I am working on a fix right now. Expect a fix to arrive soon.

**Comment by meenbeese** [comment]
Thanks for your patience and the fix will arrive in the next release.  You can check [876f78a](https://github.com/meenbeese/Chronos/pull/17/commits/876f78aa390b84d2c22c2a04fd47997ad69258b6) for more details.
