### ISSUE TITLE
Cannot build because of missing dependencies

### ISSUE THREAD

**Issue by obfusk** [meenbeese/Chronos#73]
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients?lang=en)).

Your app has been reproducible for quite a while. Unfortunately, today's build failed because you're using dependencies from JCenter or repo.spring.io. Both of those have shut down -- see [here](https://jfrog.com/blog/jcenter-sunset/) and [here](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023/) -- resulting in failing (reproducible) builds (though you may not notice if you still happen to have them cached locally).

```
   > Could not find com.afollestad:aesthetic:0.7.2.
   > Could not resolve me.jfenn:timedatepickers:0.0.6.
```

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on Reproducible Builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds).

Thank you!

cc @IzzySoft

**Comment by meenbeese** [comment]
Thank you for your input, I was wondering why the GitHub CI had suddenly stopped working when I hadn't touched the dependencies. I guess I had it coming for using deprecated stuff, but is this a blocker for my app to be on IzzyOnDroid? I thought the pre-built APK was grabbed from GH, so it should not be a problem? 

Migrating to new libraries has been on my mind for a while, but they are used in core parts of the app and replacing them will take some time unfortunately.

**Comment by obfusk** [comment]
It's not a blocker :)

But it's certainly something we hope you can fix. For now it just means the green shield for a successful Reproducible Build has become a grey "could not build" shield and you and those using your app lose the additional verification provided by Reproducible Builds.

![image](https://github.com/user-attachments/assets/b6d1c195-e21c-4bfc-b59a-b7fef5db56e5)

**Comment by meenbeese** [comment]
That's great to hear! I linked some issues here for my reference and I will be prioritizing the replacement of these old libraries over other features.

**Comment by IzzySoft** [comment]
Ah, I see "completed", nice! Just a cautious question for orientation, as that's already more than a month ago: any ETA for the release containing the fix, @meenbeese?

**Comment by meenbeese** [comment]
> Ah, I see "completed", nice! Just a cautious question for orientation, as that's already more than a month ago: any ETA for the release containing the fix, @meenbeese?

I would expect it to be in the next few weeks. I have been a bit busy lately but there are some issues to resolve before I can publish a new update.

**Comment by IzzySoft** [comment]
Cool, thanks! All the best for the other busy tasks as well – I can feel with you there, I can relate :see_no_evil: Same here.
