### ISSUE TITLE
[Bug] Some broken UI elements

### ISSUE THREAD

**Issue by gauze756** [meenbeese/Chronos#79]
## How to Reproduce

- check images
### Stopwatch and Timer
![tuzvfhnp4xaphqar](https://github.com/user-attachments/assets/3bb093a1-8e02-4c08-9672-9e32b2cdef0a)
![4feqeu24b6qnmoq4](https://github.com/user-attachments/assets/fc0f16c8-4b55-4370-a8f6-ece5241d64f9)

### Default Alarm/Timer Ringtone
![qvar9meuc5ejbdl9](https://github.com/user-attachments/assets/649a66fb-0b15-4505-b8d1-f009f80eace8)

## Info

- Device model: `Oneplus 9`
- App version: `v1.8.0`

**Comment by meenbeese** [comment]
Thanks, can you write some brief descriptions on how each of them is broken?
