### ISSUE TITLE
Notification permission not requested on Android 14

### ISSUE THREAD

**Issue by AeliusSaionji** [meenbeese/Chronos#85]
This may be related to the background crash, if only tangentially.

There's some stupid logic google implemented where an app actively showing notifications is allowed to run in the background even without background permissions, even if the user hides the notification. It may be needed in addition to background exemption.

![Screenshot_20240905-110104](https://github.com/user-attachments/assets/788d3038-9cb3-4297-a88f-69d5fc7a1f2b)

**Comment by Jean-BaptisteC** [comment]
No issue here, Chronos doesn't publish notifications :)

**Comment by AeliusSaionji** [comment]
So long as you're sure you don't need notifications for timers and stopwatches to work reliably on A14.

(A notification for each would be nice to have though)

**Comment by Jean-BaptisteC** [comment]
I have checked in the code
@meenbeese can you confirm?

**Comment by meenbeese** [comment]
> I have checked in the code @meenbeese can you confirm?

Yes and thanks for checking. Chronos has no notifications currently but I may add them in the future.

**Comment by AeliusSaionji** [comment]
I phrased this poorly: the reason I opened this issue is because Android 14 may require notifications for this app to work reliably.

I know there are currently no notifications, and that is potentially the problem.
